export const SUGGESTIONS = {
	jobTitle: [
		"Desain Grafis",
		"Teknik Informatika",
		"Manajemen",
		"Akuntansi",
		"Hukum",
		"Kedokteran",
		"Frontend Developer",
		"Backend Developer",
		"Fullstack Developer",
		"UI/UX Designer",
		"Product Designer",
		"Data Analyst",
		"Data Scientist",
		"Mobile Developer",
		"Cyber Security Specialist",
		"Cloud Engineer",
		"System Administrator",
		"DevOps Engineer",
		"Project Manager",
		"Digital Marketer",
		"Content Writer",
		"Social Media Specialist",
		"Business Analyst",
		"Quality Assurance",
		"Network Engineer",
		"Game Developer",
		"Copywriter",
		"SEO Specialist",
		"Video Editor",
		"Animator",
	],
	degree: [
		"Sarjana (S.Kom)",
		"Sarjana (S.T)",
		"Sarjana (S.Ds)",
		"Sarjana (S.M)",
		"Sarjana (S.Ak)",
		"Diploma III (A.Md.Kom)",
		"Diploma III (A.Md)",
		"Magister (M.Kom)",
		"Magister (M.T)",
		"Magister (M.B.A)",
		"Doktor (Dr.)",
		"SMA",
		"SMK",
	],
	field: [
		"Teknik Informatika",
		"Sistem Informasi",
		"Desain Komunikasi Visual",
		"Manajemen",
		"Akuntansi",
		"Teknik Elektro",
		"Teknik Industri",
		"Ilmu Komunikasi",
		"Sastra Inggris",
		"Matematika",
		"Statistika",
		"Hukum",
		"Psikologi",
		"Hubungan Internasional",
	],
	position: [
		"Frontend Developer",
		"Backend Developer",
		"Fullstack Developer",
		"UI/UX Designer",
		"UI/UX Writer",
		"Product Manager",
		"Data Analyst",
		"Quality Assurance Engineer",
		"Cyber Security Consultant",
		"Social Media Coordinator",
		"Graphic Designer",
		"Video Editor",
		"Content Creator",
		"Project Leader",
		"Creative Director",
		"Software Engineer Intern",
		"Research Assistant",
		"Teaching Assistant",
		"Freelance Developer",
	],
	role: [
		"Ketua",
		"Wakil Ketua",
		"Sekretaris",
		"Bendahara",
		"Koordinator",
		"Anggota",
		"Penanggung Jawab",
		"Kepala Divisi",
		"Staff Ahli",
		"Relawan",
		"Moderator",
		"Project Manager",
		"Event Organizer",
	],
	issuer: [
		"Google",
		"Coursera",
		"Udemy",
		"Microsoft",
		"Amazon Web Services (AWS)",
		"IBM",
		"Cisco",
		"Oracle",
		"Red Hat",
		"Dicoding Indonesia",
		"Binar Academy",
		"Sanbercode",
		"HackerRank",
		"freeCodeCamp",
		"Project Management Institute (PMI)",
		"Scrum.org",
	],
	language: [
		"Indonesia",
		"Inggris",
		"Mandarin",
		"Jepang",
		"Korea",
		"Arab",
		"Jerman",
		"Prancis",
		"Spanyol",
		"Rusia",
		"Belanda",
		"Italia",
	],
	location: [
		"Banyumas, Indonesia",
		"Purwokerto, Indonesia",
		"Cilacap, Indonesia",
		"Purbalingga, Indonesia",
		"Kebumen, Indonesia",
		"Banjarnegara, Indonesia",
		"Brebes, Indonesia",
		"Tegal, Indonesia",
		"Pekalongan, Indonesia",
		"Semarang, Indonesia",
		"Surakarta, Indonesia",
		"Yogyakarta, Indonesia",
		"Jakarta, Indonesia",
		"Bandung, Indonesia",
		"Surabaya, Indonesia",
	],
};
