<?php

namespace App\Modules\Wims\Services\Shared\Absence;

use App\Models\Magang\AbsensiMagang;
use App\Models\Magang\HariLibur;
use App\Models\Magang\KetidakhadiranMagang;
use App\Models\Magang\PendaftaranMagang;
use App\Models\User;
use App\Modules\Wims\Services\Shared\Attendance\AttendanceSyncService;
use Carbon\CarbonInterface;
use Carbon\CarbonPeriod;
use Illuminate\Support\Carbon;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class KetidakhadiranService
{
    public function __construct(
        private readonly AttendanceSyncService $attendanceSyncService,
    ) {
    }

    public function validateSubmission(PendaftaranMagang $pendaftaran, array $attributes): array
    {
        $startDate = Carbon::parse($attributes['tanggal_mulai'])->startOfDay();
        $endDate = Carbon::parse($attributes['tanggal_selesai'])->startOfDay();

        if ($endDate->lessThan($startDate)) {
            throw ValidationException::withMessages([
                'tanggal_selesai' => 'Tanggal selesai harus sama atau setelah tanggal mulai.',
            ]);
        }

        if (
            blank($pendaftaran->tanggal_mulai)
            || blank($pendaftaran->tanggal_selesai)
            || $startDate->lessThan(Carbon::parse($pendaftaran->tanggal_mulai)->startOfDay())
            || $endDate->greaterThan(Carbon::parse($pendaftaran->tanggal_selesai)->startOfDay())
        ) {
            throw ValidationException::withMessages([
                'tanggal_mulai' => 'Rentang tanggal harus berada dalam periode PKL mahasiswa.',
            ]);
        }

        $existingOverlap = KetidakhadiranMagang::query()
            ->where('pendaftaran_id', $pendaftaran->id)
            ->whereIn('status', ['pending', 'approved'])
            ->where(function ($query) use ($startDate, $endDate): void {
                $query
                    ->whereBetween('tanggal_mulai', [$startDate->toDateString(), $endDate->toDateString()])
                    ->orWhereBetween('tanggal_selesai', [$startDate->toDateString(), $endDate->toDateString()])
                    ->orWhere(function ($nested) use ($startDate, $endDate): void {
                        $nested
                            ->whereDate('tanggal_mulai', '<=', $startDate->toDateString())
                            ->whereDate('tanggal_selesai', '>=', $endDate->toDateString());
                    });
            })
            ->exists();

        if ($existingOverlap) {
            throw ValidationException::withMessages([
                'tanggal_mulai' => 'Sudah ada pengajuan ketidakhadiran yang overlap pada rentang tanggal tersebut.',
            ]);
        }

        $holidayLookup = $this->getHolidayLookup($startDate, $endDate);
        $workDates = $this->resolveApplicableWorkDates($pendaftaran, $startDate, $endDate, $holidayLookup);

        if ($workDates->isEmpty()) {
            throw ValidationException::withMessages([
                'tanggal_mulai' => 'Rentang tanggal yang dipilih tidak mengandung hari kerja aktif PKL.',
            ]);
        }

        $existingAttendance = AbsensiMagang::query()
            ->where('pendaftaran_id', $pendaftaran->id)
            ->whereIn('tanggal', $workDates->all())
            ->get()
            ->contains(fn (AbsensiMagang $attendance) => $this->attendanceSyncService->isManualAttendanceLocked($attendance));

        if ($existingAttendance) {
            throw ValidationException::withMessages([
                'tanggal_mulai' => 'Sebagian tanggal sudah memiliki data presensi nyata, sehingga pengajuan tidak dapat dibuat.',
            ]);
        }

        return [
            'start_date' => $startDate,
            'end_date' => $endDate,
            'work_dates' => $workDates,
        ];
    }

    public function approve(KetidakhadiranMagang $ketidakhadiran, User $reviewer, ?string $catatanMitra = null): void
    {
        DB::transaction(function () use ($ketidakhadiran, $reviewer, $catatanMitra): void {
            $ketidakhadiran->update([
                'status' => 'approved',
                'reviewed_by_mitra_user_id' => $reviewer->id,
                'reviewed_by_mitra_at' => now(),
                'catatan_mitra' => $catatanMitra,
            ]);

            $this->syncApprovedAttendanceRows($ketidakhadiran);
        });
    }

    public function reject(KetidakhadiranMagang $ketidakhadiran, User $reviewer, ?string $catatanMitra = null): void
    {
        DB::transaction(function () use ($ketidakhadiran, $reviewer, $catatanMitra): void {
            $ketidakhadiran->update([
                'status' => 'rejected',
                'reviewed_by_mitra_user_id' => $reviewer->id,
                'reviewed_by_mitra_at' => now(),
                'catatan_mitra' => $catatanMitra,
            ]);

            $this->deleteAutoGeneratedAttendanceRows($ketidakhadiran);
            $this->attendanceSyncService->syncForRegistration(
                $ketidakhadiran->pendaftaran()->with('perusahaan')->firstOrFail()
            );
        });
    }

    public function cancel(KetidakhadiranMagang $ketidakhadiran): void
    {
        DB::transaction(function () use ($ketidakhadiran): void {
            $ketidakhadiran->update([
                'status' => 'cancelled',
                'cancelled_at' => now(),
            ]);

            $this->deleteAutoGeneratedAttendanceRows($ketidakhadiran);
            $this->attendanceSyncService->syncForRegistration(
                $ketidakhadiran->pendaftaran()->with('perusahaan')->firstOrFail()
            );
        });
    }

    public function hasApprovedAbsenceOnDate(PendaftaranMagang $pendaftaran, CarbonInterface $date): bool
    {
        return KetidakhadiranMagang::query()
            ->where('pendaftaran_id', $pendaftaran->id)
            ->where('status', 'approved')
            ->whereDate('tanggal_mulai', '<=', $date->toDateString())
            ->whereDate('tanggal_selesai', '>=', $date->toDateString())
            ->exists();
    }

    public function getApprovedAbsenceOnDate(PendaftaranMagang $pendaftaran, CarbonInterface $date): ?KetidakhadiranMagang
    {
        return KetidakhadiranMagang::query()
            ->where('pendaftaran_id', $pendaftaran->id)
            ->where('status', 'approved')
            ->whereDate('tanggal_mulai', '<=', $date->toDateString())
            ->whereDate('tanggal_selesai', '>=', $date->toDateString())
            ->latest('id')
            ->first();
    }

    public function resolveApplicableWorkDates(
        PendaftaranMagang $pendaftaran,
        CarbonInterface $startDate,
        CarbonInterface $endDate,
        ?Collection $holidayLookup = null,
    ): Collection {
        $holidayLookup ??= $this->getHolidayLookup($startDate, $endDate);

        return collect(CarbonPeriod::create($startDate, $endDate))
            ->filter(fn (Carbon $date) => $pendaftaran->perusahaan?->worksOnDate($date, $holidayLookup))
            ->map(fn (Carbon $date) => $date->toDateString())
            ->values();
    }

    private function syncApprovedAttendanceRows(KetidakhadiranMagang $ketidakhadiran): void
    {
        $pendaftaran = $ketidakhadiran->pendaftaran()->with('perusahaan')->firstOrFail();
        $workDates = $this->resolveApplicableWorkDates(
            $pendaftaran,
            Carbon::parse($ketidakhadiran->tanggal_mulai)->startOfDay(),
            Carbon::parse($ketidakhadiran->tanggal_selesai)->startOfDay(),
        );

        foreach ($workDates as $date) {
            $attendance = AbsensiMagang::query()->firstOrNew([
                'pendaftaran_id' => $pendaftaran->id,
                'tanggal' => $date,
            ]);

            if ($this->attendanceSyncService->isManualAttendanceLocked($attendance)) {
                continue;
            }

            $attendance->fill([
                'status' => $ketidakhadiran->jenis === 'sakit' ? 'sakit' : 'izin',
                'keterangan' => $ketidakhadiran->alasan,
                'lokasi_valid' => false,
                'waktu_masuk' => null,
                'waktu_keluar' => null,
                'timestamp_masuk' => null,
                'timestamp_keluar' => null,
                'latitude_masuk' => null,
                'longitude_masuk' => null,
                'latitude_keluar' => null,
                'longitude_keluar' => null,
                'distance_masuk' => null,
                'distance_keluar' => null,
                'foto_bukti_path' => null,
                'foto_bukti_checkout_path' => null,
                'ip_address' => null,
                'user_agent' => null,
            ]);
            $attendance->save();
        }
    }

    private function deleteAutoGeneratedAttendanceRows(KetidakhadiranMagang $ketidakhadiran): void
    {
        AbsensiMagang::query()
            ->where('pendaftaran_id', $ketidakhadiran->pendaftaran_id)
            ->whereBetween('tanggal', [
                $ketidakhadiran->tanggal_mulai->toDateString(),
                $ketidakhadiran->tanggal_selesai->toDateString(),
            ])
            ->whereIn('status', ['izin', 'sakit'])
            ->whereNull('timestamp_masuk')
            ->whereNull('waktu_masuk')
            ->delete();
    }

    private function getHolidayLookup(CarbonInterface $startDate, CarbonInterface $endDate): Collection
    {
        return HariLibur::query()
            ->where('is_active', true)
            ->whereBetween('tanggal', [$startDate->toDateString(), $endDate->toDateString()])
            ->pluck('tanggal')
            ->map(fn ($date) => Carbon::parse($date)->toDateString())
            ->flip();
    }
}
