[opcache]
opcache.enable=1
opcache.enable_cli=1

; Alokasikan RAM 256MB khusus untuk OPcache (dari total 16GB)
opcache.memory_consumption=256

; Ukuran memori untuk penyimpanan string konstan unik (interned strings)
opcache.interned_strings_buffer=16

; Batas jumlah file PHP yang dapat disimpan di cache
opcache.max_accelerated_files=20000

; Matikan validasi timestamp agar PHP tidak perlu memeriksa perubahan file di disk pada setiap request
opcache.validate_timestamps=0

; Kecepatan shutdown/pembersihan memori
opcache.fast_shutdown=1
