<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import {
    ArrowDown,
    ArrowUp,
    CalendarRange,
    ClipboardList,
    PencilLine,
    Plus,
    Save,
    Search,
    Trash2,
} from 'lucide-vue-next';
import InputError from '@/components/InputError.vue';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import WimsAdminLayout from '@/layouts/Modules/Wims/Admin/Layout.vue';
import wimsRoutes from '@/routes/wims';

defineOptions({
    layout: WimsAdminLayout,
});

type Summary = {
    total_templates?: number;
    active_templates?: number;
    active_dosen_templates?: number;
    active_mitra_templates?: number;
    active_shared_templates?: number;
    default_components?: number;
    available_years?: number;
};

type YearOption = {
    value: string;
    label: string;
    periode_mulai: string;
    periode_selesai: string;
    periode_label: string;
};

type TemplateComponent = {
    id?: number;
    name: string;
    description?: string | null;
    weight_percentage: number | string;
    sort_order: number;
};

type TemplateItem = {
    id: number;
    year?: string | null;
    name: string;
    description?: string | null;
    assessor_role: 'dosen' | 'mitra' | 'both';
    assessor_role_label?: string;
    is_active: boolean;
    periode_mulai: string;
    periode_selesai: string;
    periode_label: string;
    components: TemplateComponent[];
    component_count: number;
    total_weight: number;
    created_at?: string | null;
};

const props = defineProps<{
    filters: {
        search?: string;
        template?: number | null;
        assessor_role?: 'dosen' | 'mitra' | 'both' | '';
    };
    summary: Summary;
    templates: TemplateItem[];
    years: YearOption[];
    roleOptions: Array<{
        value: 'dosen' | 'mitra' | 'both';
        label: string;
    }>;
    defaultComponents: TemplateComponent[];
}>();

const search = ref(props.filters.search || '');
const selectedTemplateId = ref<number | null>(props.filters.template ?? null);
const workspaceRole = ref<'dosen' | 'mitra'>(
    props.filters.assessor_role === 'mitra' ? 'mitra' : 'dosen',
);
const selectedYear = ref('');
const autoGeneratedName = ref('');

const buildDefaultComponents = () =>
    props.defaultComponents.map((component, index) => ({
        id: component.id,
        name: component.name,
        description: component.description ?? '',
        weight_percentage: Number(component.weight_percentage),
        sort_order: index + 1,
    }));

const form = useForm({
    name: '',
    description: '',
    year: '',
    assessor_role: 'dosen' as 'dosen' | 'mitra' | 'both',
    is_active: true,
    components: buildDefaultComponents(),
});

const selectedTemplate = computed(
    () =>
        props.templates.find((item) => item.id === selectedTemplateId.value) ??
        null,
);

const visibleTemplates = computed(() =>
    props.templates.filter(
        (item) =>
            item.assessor_role === workspaceRole.value ||
            item.assessor_role === 'both',
    ),
);

const totalWeight = computed(() =>
    Number(
        form.components
            .reduce(
                (total, component) =>
                    total + Number(component.weight_percentage || 0),
                0,
            )
            .toFixed(2),
    ),
);

const isWeightValid = computed(
    () => Math.abs(totalWeight.value - 100) < 0.01 && form.components.length > 0,
);

const selectedYearOption = computed(
    () =>
        props.years.find((yearOption) => yearOption.value === selectedYear.value) ??
        null,
);

const resolveRoleLabel = (role: 'dosen' | 'mitra' | 'both') => {
    switch (role) {
        case 'mitra':
            return 'Mitra';
        case 'both':
            return 'Dosen & Mitra';
        case 'dosen':
        default:
            return 'Dosen';
    }
};

const resolveRoleBadgeClass = (role: 'dosen' | 'mitra' | 'both') => {
    switch (role) {
        case 'mitra':
            return 'border-emerald-200 bg-emerald-50 text-emerald-700';
        case 'both':
            return 'border-violet-200 bg-violet-50 text-violet-700';
        case 'dosen':
        default:
            return 'border-blue-200 bg-blue-50 text-blue-700';
    }
};

const resolveRoleDescription = (role: 'dosen' | 'mitra' | 'both') => {
    switch (role) {
        case 'mitra':
            return 'Dipakai hanya saat penilai berasal dari pihak mitra.';
        case 'both':
            return 'Satu template yang sama dipakai oleh dosen dan mitra secara bersamaan.';
        case 'dosen':
        default:
            return 'Dipakai hanya saat penilai berasal dari dosen pembimbing.';
    }
};

const workspaceTitle = computed(() =>
    workspaceRole.value === 'dosen' ? 'Dosen Pembimbing' : 'Mitra Perusahaan',
);

const useSharedTemplate = computed({
    get: () => form.assessor_role === 'both',
    set: (value: boolean) => {
        form.assessor_role = value ? 'both' : workspaceRole.value;
    },
});

const buildTemplateName = (year: string, role: 'dosen' | 'mitra' | 'both') =>
    `Template Penilaian ${resolveRoleLabel(role)} ${year}`;

const setSortOrder = () => {
    form.components = form.components.map((component, index) => ({
        ...component,
        sort_order: index + 1,
    }));
};

const fillForm = (template: TemplateItem | null) => {
    if (!template) {
        form.reset();
        form.clearErrors();
        form.name = '';
        form.description = '';
        form.year = props.years[0]?.value ?? '';
        form.assessor_role = workspaceRole.value;
        form.is_active = true;
        form.components = buildDefaultComponents();
        setSortOrder();
        selectedYear.value = props.years[0]?.value ?? '';
        autoGeneratedName.value = buildTemplateName(selectedYear.value, form.assessor_role);
        form.name = autoGeneratedName.value;
        return;
    }

    form.clearErrors();
    form.name = template.name;
    form.description = template.description ?? '';
    form.year = template.year ?? '';
    form.assessor_role = template.assessor_role;
    form.is_active = template.is_active;
    form.components = template.components.map((component, index) => ({
        id: component.id,
        name: component.name,
        description: component.description ?? '',
        weight_percentage: Number(component.weight_percentage),
        sort_order: component.sort_order ?? index + 1,
    }));
    setSortOrder();
    selectedYear.value = template.year ?? '';
    autoGeneratedName.value = template.year
        ? buildTemplateName(template.year, template.assessor_role)
        : '';
};

const startCreate = () => {
    selectedTemplateId.value = null;
    fillForm(null);
};

watch(
    () => props.filters,
    (filters) => {
        search.value = filters.search || '';
        selectedTemplateId.value = filters.template ?? null;
        workspaceRole.value = filters.assessor_role === 'mitra' ? 'mitra' : 'dosen';
    },
    { deep: true },
);

watch(
    () => props.templates,
    (templates) => {
        if (selectedTemplateId.value) {
            const match = templates.find(
                (item) => item.id === selectedTemplateId.value,
            );

            if (match) {
                fillForm(match);
                return;
            }
        }

        if (!templates.length || selectedTemplateId.value === null) {
            fillForm(null);
        }
    },
    { immediate: true, deep: true },
);

watch(selectedYearOption, (yearOption) => {
    if (!yearOption) {
        return;
    }

    form.year = yearOption.value;

    const nextAutoName = buildTemplateName(yearOption.value, form.assessor_role);

    if (form.name.trim() === '' || form.name.trim() === autoGeneratedName.value) {
        form.name = nextAutoName;
    }

    autoGeneratedName.value = nextAutoName;
});

watch(
    () => form.assessor_role,
    (role) => {
        if (!selectedYear.value) {
            return;
        }

        const nextAutoName = buildTemplateName(selectedYear.value, role);

        if (form.name.trim() === '' || form.name.trim() === autoGeneratedName.value) {
            form.name = nextAutoName;
        }

        autoGeneratedName.value = nextAutoName;
    },
);

watch(workspaceRole, (role) => {
    if (
        selectedTemplate.value &&
        selectedTemplate.value.assessor_role !== 'both' &&
        selectedTemplate.value.assessor_role !== role
    ) {
        startCreate();
        return;
    }

    if (!selectedTemplate.value && form.assessor_role !== 'both') {
        form.assessor_role = role;
    }
});

const applyFilter = () => {
    router.get(
        wimsRoutes.admin.assessmentTemplates.index().url,
        {
            search: search.value || undefined,
            template: selectedTemplateId.value || undefined,
        },
        {
            preserveState: true,
            preserveScroll: true,
            replace: true,
        },
    );
};

const selectTemplate = (template: TemplateItem) => {
    selectedTemplateId.value = template.id;
    fillForm(template);
};

const addComponent = () => {
    form.components.push({
        id: undefined,
        name: '',
        description: '',
        weight_percentage: 0,
        sort_order: form.components.length + 1,
    });
    setSortOrder();
};

const removeComponent = (index: number) => {
    if (form.components.length === 1) {
        return;
    }

    form.components.splice(index, 1);
    setSortOrder();
};

const moveComponent = (index: number, direction: 'up' | 'down') => {
    const targetIndex = direction === 'up' ? index - 1 : index + 1;

    if (targetIndex < 0 || targetIndex >= form.components.length) {
        return;
    }

    const nextComponents = [...form.components];
    const currentItem = nextComponents[index];

    nextComponents[index] = nextComponents[targetIndex];
    nextComponents[targetIndex] = currentItem;

    form.components = nextComponents;
    setSortOrder();
};

const applyDefaultTemplate = () => {
    form.components = buildDefaultComponents();
    setSortOrder();
};

const submit = () => {
    setSortOrder();

    const payload = {
        name: form.name,
        description: form.description,
        year: Number(form.year),
        assessor_role: form.assessor_role,
        is_active: form.is_active,
        components: form.components.map((component, index) => ({
            id: component.id,
            name: component.name,
            description: component.description || null,
            weight_percentage: Number(component.weight_percentage || 0),
            sort_order: index + 1,
        })),
    };

    if (selectedTemplateId.value) {
        form.transform(() => payload).put(
            wimsRoutes.admin.assessmentTemplates.update(selectedTemplateId.value)
                .url,
            {
                preserveScroll: true,
            },
        );

        return;
    }

    form.transform(() => payload).post(
        wimsRoutes.admin.assessmentTemplates.store().url,
        {
            preserveScroll: true,
        },
    );
};

const destroyTemplate = () => {
    if (!selectedTemplate.value) {
        return;
    }

    if (
        !window.confirm(
            `Hapus template "${selectedTemplate.value.name}" dari daftar?`,
        )
    ) {
        return;
    }

    router.delete(
        wimsRoutes.admin.assessmentTemplates.destroy(selectedTemplate.value.id)
            .url,
        {
            preserveScroll: true,
            onSuccess: () => {
                selectedTemplateId.value = null;
                fillForm(null);
            },
        },
    );
};

const weightClass = computed(() =>
    isWeightValid.value
        ? 'border-emerald-200 bg-emerald-50 text-emerald-700'
        : 'border-amber-200 bg-amber-50 text-amber-700',
);

const componentError = (index: number, field: 'name' | 'weight_percentage') =>
    form.errors[
        `components.${index}.${field}` as keyof typeof form.errors
    ] as string | undefined;

const submitLabel = computed(() =>
    selectedTemplate.value ? 'Simpan Perubahan' : 'Tambah Template',
);
</script>

<template>
    <Head title="Template Penilaian Admin" />

    <div
        class="mx-auto w-full max-w-[1320px] space-y-5 px-4 py-4 sm:px-6 sm:py-6 lg:space-y-6 lg:px-8 lg:py-8"
    >
        <div class="flex flex-col gap-5">
            <Card class="rounded-xl border border-zinc-200 bg-white py-0 shadow-none">
                <CardHeader class="border-b border-zinc-200 px-5 py-4">
                    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                        <div>
                            <CardTitle class="text-[15px] font-bold text-slate-950">
                                Daftar Template
                            </CardTitle>
                            <CardDescription class="mt-1 text-sm leading-6 text-slate-600">
                                Bedakan dengan jelas template khusus dosen, khusus mitra,
                                dan template bersama agar penilaian tidak ambigu.
                            </CardDescription>
                        </div>

                        <Button
                            type="button"
                            class="h-10 rounded-lg bg-blue-600 px-4 text-white hover:bg-blue-700"
                            @click="startCreate"
                        >
                            <Plus class="size-4" />
                            Buat Template Baru
                        </Button>
                    </div>
                </CardHeader>

                <CardContent class="space-y-5 px-5 py-5">
                    <div class="rounded-xl border border-zinc-200 bg-zinc-50 p-3 sm:p-4">
                        <div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
                            <div class="space-y-2">
                                <p class="text-xs font-bold uppercase tracking-[0.16em] text-slate-500">
                                    Konteks Pengaturan
                                </p>
                                <div class="flex flex-wrap gap-2">
                                    <button
                                        type="button"
                                        class="rounded-lg border px-4 py-2 text-sm font-bold transition"
                                        :class="
                                            workspaceRole === 'dosen'
                                                ? 'border-blue-300 bg-blue-50 text-blue-700'
                                                : 'border-zinc-200 bg-white text-zinc-700 hover:border-zinc-300'
                                        "
                                        @click="workspaceRole = 'dosen'"
                                    >
                                        Dosen
                                    </button>
                                    <button
                                        type="button"
                                        class="rounded-lg border px-4 py-2 text-sm font-bold transition"
                                        :class="
                                            workspaceRole === 'mitra'
                                                ? 'border-emerald-300 bg-emerald-50 text-emerald-700'
                                                : 'border-zinc-200 bg-white text-zinc-700 hover:border-zinc-300'
                                        "
                                        @click="workspaceRole = 'mitra'"
                                    >
                                        Mitra
                                    </button>
                                </div>
                            </div>

                            <div class="flex flex-wrap gap-2 text-xs font-bold">
                                <span class="rounded-full border border-zinc-200 bg-white px-2.5 py-1 text-zinc-700">
                                    Total {{ summary.total_templates ?? 0 }}
                                </span>
                                <span class="rounded-full border border-zinc-200 bg-white px-2.5 py-1 text-zinc-700">
                                    Aktif {{ summary.active_templates ?? 0 }}
                                </span>
                                <span class="rounded-full border border-violet-200 bg-violet-50 px-2.5 py-1 text-violet-700">
                                    Bersama {{ summary.active_shared_templates ?? 0 }}
                                </span>
                            </div>
                        </div>
                        <p class="mt-3 text-sm leading-6 text-zinc-600">
                            Anda sedang mengatur template untuk
                            <span class="font-semibold text-zinc-900">{{ workspaceTitle }}</span>.
                            Template bersama hanya dipakai jika dosen dan mitra menggunakan komponen serta persentase yang sama.
                        </p>
                    </div>

                    <form
                        class="flex flex-col gap-3 md:flex-row md:items-center"
                        @submit.prevent="applyFilter"
                    >
                        <div class="relative">
                            <Search
                                class="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-zinc-400"
                            />
                            <Input
                                v-model="search"
                                type="text"
                                placeholder="Cari nama template atau komponen..."
                                class="h-10 rounded-lg border-zinc-200 bg-zinc-50 pl-10 md:w-full"
                            />
                        </div>

                        <Button
                            type="submit"
                            variant="outline"
                            class="h-10 rounded-lg border-zinc-200 px-4 text-zinc-700 md:shrink-0"
                        >
                            Terapkan
                        </Button>
                    </form>

                    <div
                        class="rounded-xl border border-zinc-200 bg-white px-4 py-3"
                    >
                        <p class="text-sm font-bold">
                            Template {{ workspaceTitle }}
                        </p>
                        <p class="mt-1 text-sm leading-6 text-zinc-600">
                            Daftar di bawah menampilkan template khusus untuk {{ workspaceRole === 'dosen' ? 'dosen pembimbing' : 'mitra perusahaan' }} dan template bersama yang juga berlaku untuk role ini.
                        </p>
                    </div>

                    <div v-if="visibleTemplates.length" class="space-y-4">
                        <button
                            v-for="template in visibleTemplates"
                            :key="template.id"
                            type="button"
                            class="w-full rounded-xl border px-4 py-4 text-left transition"
                            :class="
                                selectedTemplateId === template.id
                                    ? 'border-blue-200 bg-blue-50'
                                    : 'border-zinc-200 bg-white hover:border-zinc-300 hover:bg-zinc-50'
                            "
                            @click="selectTemplate(template)"
                        >
                            <div class="flex items-start justify-between gap-3">
                                <div class="min-w-0">
                                    <div class="flex flex-wrap items-center gap-2">
                                        <Badge
                                            variant="outline"
                                            class="rounded-full px-2.5 py-0.5 text-[10px] font-bold shadow-none"
                                            :class="resolveRoleBadgeClass(template.assessor_role)"
                                        >
                                            {{ template.assessor_role_label || resolveRoleLabel(template.assessor_role) }}
                                        </Badge>
                                        <Badge
                                            variant="outline"
                                            class="rounded-full border-slate-200 bg-slate-50 px-2.5 py-0.5 text-[10px] font-bold text-slate-700 shadow-none"
                                        >
                                            Tahun {{ template.year || '-' }}
                                        </Badge>
                                        <p class="truncate text-sm font-bold text-zinc-950">
                                            {{ template.name }}
                                        </p>
                                        <Badge
                                            variant="outline"
                                            class="rounded-full px-2.5 py-0.5 text-[10px] font-bold shadow-none"
                                            :class="
                                                template.is_active
                                                    ? 'border-emerald-200 bg-emerald-50 text-emerald-700'
                                                    : 'border-zinc-200 bg-zinc-100 text-zinc-600'
                                            "
                                        >
                                            {{ template.is_active ? 'Aktif' : 'Nonaktif' }}
                                        </Badge>
                                    </div>
                                    <p class="mt-1 text-sm text-zinc-500">
                                        Berlaku untuk {{ template.periode_label }}
                                    </p>
                                    <p class="mt-1 text-xs font-medium text-zinc-500">
                                        {{ resolveRoleDescription(template.assessor_role) }}
                                    </p>
                                    <p
                                        v-if="template.description"
                                        class="mt-2 line-clamp-2 text-sm leading-6 text-zinc-500"
                                    >
                                        {{ template.description }}
                                    </p>
                                </div>

                                <PencilLine class="mt-0.5 size-4 shrink-0 text-zinc-400" />
                            </div>

                            <div class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                                <div class="rounded-lg border border-zinc-200 bg-white px-3 py-2.5">
                                    <p class="text-[11px] font-bold uppercase tracking-[0.16em] text-slate-500">Tahun</p>
                                    <p class="mt-1 text-sm font-bold text-zinc-950">
                                        {{ template.year || '-' }}
                                    </p>
                                </div>
                                <div class="rounded-lg border border-zinc-200 bg-white px-3 py-2.5">
                                    <p class="text-[11px] font-bold uppercase tracking-[0.16em] text-slate-500">Total bobot</p>
                                    <p class="mt-1 text-sm font-bold text-zinc-950">
                                        {{ template.total_weight }}%
                                    </p>
                                </div>
                                <div class="rounded-lg border border-zinc-200 bg-white px-3 py-2.5">
                                    <p class="text-[11px] font-bold uppercase tracking-[0.16em] text-slate-500">Komponen</p>
                                    <p class="mt-1 text-sm font-bold text-zinc-950">
                                        {{ template.component_count }}
                                    </p>
                                </div>
                                <div class="rounded-lg border border-zinc-200 bg-white px-3 py-2.5">
                                    <p class="text-[11px] font-bold uppercase tracking-[0.16em] text-slate-500">Role</p>
                                    <p class="mt-1 text-sm font-bold text-zinc-950">
                                        {{ template.assessor_role_label || resolveRoleLabel(template.assessor_role) }}
                                    </p>
                                </div>
                            </div>
                        </button>
                    </div>

                    <div
                        v-else
                        class="rounded-xl border border-dashed border-zinc-200 bg-zinc-50 px-5 py-6 text-center"
                    >
                        <p class="text-sm font-bold text-zinc-700">
                            Belum ada template penilaian.
                        </p>
                        <p class="mt-2 text-sm text-zinc-500">
                            Mulai dari template default lalu sesuaikan untuk tahun PKL yang dibutuhkan.
                        </p>
                    </div>
                </CardContent>
            </Card>

            <Card class="rounded-xl border border-zinc-200 bg-white py-0 shadow-none">
                <CardHeader class="border-b border-zinc-200 px-5 py-4">
                    <div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                        <div>
                            <CardTitle class="text-[15px] font-bold text-slate-950">
                                {{ selectedTemplate ? 'Kelola Template' : 'Template Baru' }}
                            </CardTitle>
                            <CardDescription class="mt-1 text-sm leading-6 text-slate-600">
                                Atur template untuk {{ workspaceRole === 'dosen' ? 'dosen pembimbing' : 'penilai mitra' }}, lalu aktifkan template bersama hanya jika kedua role memakai komponen dan bobot yang sama.
                            </CardDescription>
                        </div>

                        <div class="flex flex-wrap items-center gap-2">
                            <Button
                                type="button"
                                variant="outline"
                                class="h-10 rounded-lg border-zinc-200 px-4 text-zinc-700"
                                @click="applyDefaultTemplate"
                            >
                                <ClipboardList class="size-4" />
                                Gunakan Template Default
                            </Button>
                            <Button
                                v-if="selectedTemplate"
                                type="button"
                                variant="outline"
                                class="h-10 rounded-lg border-rose-200 px-4 text-rose-700 hover:bg-rose-50"
                                @click="destroyTemplate"
                            >
                                <Trash2 class="size-4" />
                                Hapus
                            </Button>
                        </div>
                    </div>
                </CardHeader>

                <CardContent class="space-y-5 px-5 py-5">
                    <div class="grid gap-4 md:grid-cols-2">
                        <div class="space-y-2">
                            <label class="text-sm font-bold text-zinc-900">Tahun Penilaian</label>
                            <select
                                v-model="selectedYear"
                                class="h-10 w-full rounded-lg border border-zinc-200 bg-zinc-50 px-3 text-sm text-zinc-900 outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-600/10"
                            >
                                <option value="">Pilih tahun PKL</option>
                                <option
                                    v-for="yearOption in years"
                                    :key="yearOption.value"
                                    :value="yearOption.value"
                                >
                                    {{ yearOption.label }}
                                </option>
                            </select>
                            <InputError :message="form.errors.year" />
                        </div>

                        <div class="space-y-2">
                            <label class="text-sm font-bold text-zinc-900">Cakupan Template</label>
                            <div class="rounded-xl border border-zinc-200 bg-zinc-50 p-4">
                                <div class="flex items-start gap-3">
                                    <input
                                        id="shared-template"
                                        v-model="useSharedTemplate"
                                        type="checkbox"
                                        class="mt-0.5 size-4 rounded border-zinc-300 text-blue-600 focus:ring-blue-600/20"
                                    />
                                    <div>
                                        <label for="shared-template" class="text-sm font-bold text-zinc-900">
                                            Gunakan template yang sama untuk dosen dan mitra
                                        </label>
                                        <p class="mt-1 text-xs leading-5 text-zinc-500">
                                            Jika dinonaktifkan, form ini menyimpan template khusus untuk {{ workspaceRole === 'dosen' ? 'dosen' : 'mitra' }}. Jika diaktifkan, template yang sama akan dipakai oleh kedua role.
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <InputError :message="form.errors.assessor_role" />
                        </div>

                        <div class="flex items-end">
                            <label
                                class="inline-flex items-center gap-3 rounded-lg border border-zinc-200 bg-zinc-50 px-4 py-2.5 text-sm text-zinc-700"
                            >
                                <input
                                    v-model="form.is_active"
                                    type="checkbox"
                                    class="size-4 rounded border-zinc-300 text-blue-600 focus:ring-blue-600/20"
                                />
                                Template aktif tahun ini
                            </label>
                        </div>
                    </div>

                    <div class="space-y-2">
                        <label class="text-sm font-bold text-zinc-900">
                            Nama template
                        </label>
                        <Input
                            v-model="form.name"
                            type="text"
                            placeholder="Template Penilaian PKL 2026"
                            class="h-10 rounded-lg border-zinc-200 bg-zinc-50"
                        />
                        <InputError :message="form.errors.name" />
                        <p
                            v-if="selectedYearOption"
                            class="text-xs text-zinc-500"
                        >
                            Berlaku untuk {{ selectedYearOption.periode_label }}
                        </p>
                        <p class="text-xs text-zinc-500">
                            Template ini akan disimpan sebagai
                            <span class="font-semibold">
                                {{ form.assessor_role === 'both' ? 'Template Bersama' : workspaceRole === 'dosen' ? 'Template Khusus Dosen' : 'Template Khusus Mitra' }}
                            </span>.
                        </p>
                    </div>

                    <div class="space-y-2">
                        <label class="text-sm font-bold text-zinc-900">
                            Deskripsi
                        </label>
                        <textarea
                            v-model="form.description"
                            rows="3"
                            class="min-h-24 w-full rounded-lg border border-zinc-200 bg-zinc-50 px-3 py-2.5 text-sm text-zinc-900 outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-600/10"
                            placeholder="Tambahkan catatan penggunaan template bila diperlukan."
                        />
                        <InputError :message="form.errors.description" />
                    </div>

                    <div class="rounded-xl border border-zinc-200 bg-zinc-50 p-4">
                        <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                            <div>
                                <p class="text-sm font-bold text-zinc-950">
                                    Komponen Penilaian
                                </p>
                                <p class="mt-1 text-sm text-zinc-500">
                                    Gunakan komponen yang sama untuk semua mahasiswa PKL tahun {{ selectedYear || 'ini' }}.
                                </p>
                            </div>

                            <Button
                                type="button"
                                variant="outline"
                                class="h-10 rounded-lg border-zinc-200 bg-white px-4 text-zinc-700"
                                @click="addComponent"
                            >
                                <Plus class="size-4" />
                                Tambah Komponen
                            </Button>
                        </div>

                        <InputError class="mt-3" :message="form.errors.components" />

                        <div class="mt-4 overflow-hidden rounded-xl border border-zinc-200 bg-white">
                            <div class="overflow-x-auto">
                                <table class="w-full table-fixed border-collapse">
                                    <colgroup>
                                        <col class="w-14" />
                                        <col />
                                        <col class="w-[120px]" />
                                        <col class="w-[148px]" />
                                    </colgroup>
                                    <thead>
                                        <tr class="border-b border-zinc-200 bg-zinc-50">
                                            <th class="px-4 py-3 text-left text-[11px] font-bold tracking-[0.16em] text-slate-500 uppercase">
                                                No
                                            </th>
                                            <th class="px-4 py-3 text-left text-[11px] font-bold tracking-[0.16em] text-slate-500 uppercase">
                                                Nama Komponen
                                            </th>
                                            <th class="px-4 py-3 text-left text-[11px] font-bold tracking-[0.16em] text-slate-500 uppercase">
                                                Bobot %
                                            </th>
                                            <th class="px-4 py-3 text-right text-[11px] font-bold tracking-[0.16em] text-slate-500 uppercase">
                                                Aksi
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr
                                            v-for="(component, index) in form.components"
                                            :key="`desktop-${index}-${component.sort_order}`"
                                            class="border-b border-zinc-200 align-top last:border-b-0"
                                        >
                                            <td class="px-4 py-3 text-sm font-bold text-zinc-700">
                                                {{ index + 1 }}
                                            </td>
                                            <td class="px-4 py-2">
                                                <Input
                                                    v-model="component.name"
                                                    type="text"
                                                    placeholder="Contoh: Disiplin"
                                                    class="h-10 w-full rounded-lg border-zinc-200 bg-zinc-50"
                                                />
                                                <InputError
                                                    class="mt-1"
                                                    :message="componentError(index, 'name')"
                                                />
                                            </td>
                                            <td class="px-4 py-2">
                                                <Input
                                                    v-model="component.weight_percentage"
                                                    type="number"
                                                    min="0"
                                                    step="0.01"
                                                    class="h-10 w-full rounded-lg border-zinc-200 bg-zinc-50"
                                                />
                                                <InputError
                                                    class="mt-1"
                                                    :message="componentError(index, 'weight_percentage')"
                                                />
                                            </td>
                                            <td class="px-4 py-2">
                                                <div class="flex items-center justify-end gap-2">
                                                    <Button
                                                        type="button"
                                                        variant="outline"
                                                        size="sm"
                                                        class="h-9 w-9 rounded-lg border-zinc-200 p-0 text-zinc-700"
                                                        :disabled="index === 0"
                                                        @click="moveComponent(index, 'up')"
                                                    >
                                                        <ArrowUp class="size-4" />
                                                    </Button>
                                                    <Button
                                                        type="button"
                                                        variant="outline"
                                                        size="sm"
                                                        class="h-9 w-9 rounded-lg border-zinc-200 p-0 text-zinc-700"
                                                        :disabled="index === form.components.length - 1"
                                                        @click="moveComponent(index, 'down')"
                                                    >
                                                        <ArrowDown class="size-4" />
                                                    </Button>
                                                    <Button
                                                        type="button"
                                                        variant="outline"
                                                        size="sm"
                                                        class="h-9 w-9 rounded-lg border-rose-200 p-0 text-rose-700 hover:bg-rose-50"
                                                        :disabled="form.components.length === 1"
                                                        @click="removeComponent(index)"
                                                    >
                                                        <Trash2 class="size-4" />
                                                    </Button>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="flex flex-col gap-4 rounded-xl border border-zinc-200 bg-white px-4 py-4 sm:flex-row sm:items-center sm:justify-between">
                        <div class="flex items-center gap-3">
                            <div
                                class="flex size-10 items-center justify-center rounded-lg bg-zinc-100 text-zinc-600"
                            >
                                <CalendarRange class="size-4" />
                            </div>
                            <div>
                                <p class="text-sm font-bold text-zinc-700">
                                    Total Bobot
                                </p>
                                <p class="mt-1 text-sm text-zinc-500">
                                    Tombol simpan aktif saat total bobot tepat 100%.
                                </p>
                                <p
                                    v-if="!isWeightValid"
                                    class="mt-1 text-xs text-amber-700"
                                >
                                    Sesuaikan bobot komponen agar total tepat 100%.
                                </p>
                            </div>
                        </div>

                        <div
                            class="inline-flex items-center rounded-lg border px-4 py-2 text-sm font-bold"
                            :class="weightClass"
                        >
                            {{ totalWeight }}%
                            <span class="ml-2 text-xs font-bold">
                                {{ isWeightValid ? 'Valid' : 'Total belum 100%' }}
                            </span>
                        </div>
                    </div>

                    <div
                        class="sticky bottom-0 z-20 -mx-5 flex flex-col-reverse gap-3 border-t border-zinc-200 bg-white px-5 py-4 shadow-[0_-8px_18px_rgba(15,23,42,0.06)] sm:mx-0 sm:flex-row sm:items-center sm:justify-end sm:px-0"
                    >
                        <div class="flex w-full flex-col gap-2 sm:w-auto sm:flex-row sm:items-center">
                            <Button
                                type="button"
                                variant="outline"
                                class="h-9 rounded-lg border-zinc-200 px-4 text-sm font-bold text-zinc-700 sm:w-auto"
                                @click="startCreate"
                            >
                                Reset Form
                            </Button>
                            <Button
                                type="button"
                                class="h-9 rounded-lg bg-blue-600 px-4 text-sm font-bold text-white hover:bg-blue-700 disabled:bg-zinc-100 disabled:text-zinc-400 disabled:hover:bg-zinc-100 sm:w-auto"
                                :disabled="form.processing || !isWeightValid"
                                @click="submit"
                            >
                                <Save class="size-4" />
                                {{ form.processing ? 'Menyimpan...' : submitLabel }}
                            </Button>
                        </div>
                    </div>
                </CardContent>
            </Card>
        </div>

    </div>
</template>
